version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:15"
    labels:
      - "Automatic"
    open-pull-requests-limit: 99
