name: ASF-auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR if deemed appropriate
        uses: JustArchi/action-dependabot-auto-merge@24c89abc11953af26fe32a1e5640d3ad80352016
        with:
          github-token: ${{ secrets.PERSONAL_TEST }}
          target: digest
